# application-docker.properties
spring.application.name=backend
server.port=8080

# PostgreSQL – используем имя сервиса из docker-compose
spring.datasource.url=jdbc:postgresql://postgres:5432/messenger
spring.datasource.username=messenger_user
spring.datasource.password=messenger_pass

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# MinIO
minio.url=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=messenger-files

# JWT
jwt.secret=${JWT_SECRET:yourSecretKeyAtLeast32CharactersLongPleaseChangeInProductionForSecurity}
jwt.expiration=900000
jwt.refresh-expiration=2592000000

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://bonds-app.duckdns.org}

# Email (2FA) - через Resend HTTP API (порт 443, не блокируется DigitalOcean)
resend.api-key=${RESEND_API_KEY:}
resend.from-address=${RESEND_FROM_ADDRESS:Bonds <onboarding@resend.dev>}

# Логирование
logging.level.org.springframework.web.socket=INFO
logging.level.org.springframework.messaging=INFO

#MaxUploadSize
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB